
CREATE DATABASE ALMACEN2016
GO
USE ALMACEN2016

GO

CREATE TABLE CLIENTE
(NOMBRE VARCHAR(15) PRIMARY KEY,
 CLAVE VARCHAR(15),
  ESTADO VARCHAR(2))
  GO

  CREATE TABLE PREESTADISTICAS
  (# INT ,
   CANTIDAS_PREMIOS_ENTREGADOS INT,
   CANTIDAD_JUEGOS_REALIZADOS INT,
   VALOR_SORTEO FLOAT)

   CREATE TABLE GANADORES
   (# INT IDENTITY,
    VALOR_GANADO FLOAT)

 GO

 ALTER TABLE  CLIENTE 
 ADD CHECK (ESTADO IN ('SI', 'NO') )
 
 GO
 
 INSERT INTO CLIENTE VALUES
 ('X','X','NO'),
 ('ALETEMATE','1234', 'NO'),
 ('JUAN25','1234', 'SI'),
 ('ANA47','1234', 'SI'),
 ('GABRIL2','1234', 'NO'),
 ('ANTONIO21','1234', 'NO'),
 ('IVAN12','1234', 'NO'),
 ('ALEJO04','1234', 'NO'),
 ('JUANITO4','1234', 'NO'),
 ('ELVER4','1234', 'NO'),
 ('WADY2','1234', 'NO'),
 ('ALEJA78','1234', 'NO'),
 ('ANALO1','1234', 'NO'),
 ('NOHAVA2','1234', 'NO'),
 ('NEO2','1234', 'NO'),
 ('SOFIA12','1234', 'NO'),
 ('LUISA12','1234', 'NO'),
 ('JORGE23','1234', 'NO'),
 ('JAMES45','1234', 'NO'),
 ('FELIPE12','1234', 'NO'),
 ('PIPE123','1234', 'NO'),
 ('CAMILO12','1234', 'NO'),
 ('ISABEL23','1234', 'NO'),
 ('ASTRIN9','1234', 'NO'),
 ('CRISTIAN48','1234', 'NO'),
 ('DAVID34','1234', 'NO'),
 ('JOHANA08','1234', 'NO'),
 ('LEIDY24','1234', 'NO'),
 ('MANUEL78','1234', 'NO'),
 ('JUANA21','1234', 'NO'),
 ('JENNY23','1234', 'NO')

 GO
 INSERT INTO PREESTADISTICAS VALUES
 (1,0,0,0)

 
 --APARTIR DE ACA ES CODIGO QUE SE USO PARA EL TESTING
 GO
 SELECT * FROM PREESTADISTICAS
 SELECT * FROM CLIENTE 
 SELECT * FROM GANADORES
 
 UPDATE CLIENTE SET ESTADO = 'NO' WHERE NOMBRE = 'X'

               UPDATE PREESTADISTICAS SET CANTIDAS_PREMIOS_ENTREGADOS= CANTIDAS_PREMIOS_ENTREGADOS + 1 WHERE # = '1'

			   UPDATE PREESTADISTICAS SET CANTIDAS_PREMIOS_ENTREGADOS= 0 WHERE # = 1
			   UPDATE PREESTADISTICAS SET CANTIDAD_JUEGOS_REALIZADOS= 0 WHERE # = 1
			   UPDATE PREESTADISTICAS SET VALOR_SORTEO= 0 WHERE # = 1
			   DELETE   FROM GANADORES
			  
			   


